## Indexing & Slicing

In [1]:
import numpy as np

In [3]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[2]) 

30


In [4]:
print("Last element:", arr[-1])  

Last element: 50


In [5]:
arr2D = np.array([[10, 20, 30], [40, 50, 60]])
print("Element at row 1, column 2:", arr2D[1, 2])  

Element at row 1, column 2: 60


In [6]:
arr = np.array([10, 20, 30, 40, 50, 60])

print("Slice from index 1 to 4:", arr[1:4])  # [20, 30, 40]
print("Every second element:", arr[::2])  # [10, 30, 50]
print("Reversed array:", arr[::-1])  # [60, 50, 40, 30, 20, 10]


Slice from index 1 to 4: [20 30 40]
Every second element: [10 30 50]
Reversed array: [60 50 40 30 20 10]


In [8]:
arr2D = np.array([[10, 20, 30], 
                  [40, 50, 60], 
                  [70, 80, 90]])
# Extract first two rows and first two columns
print("Subarray:\n", arr2D[:2, :2])

Subarray:
 [[10 20]
 [40 50]]


### **Advanced Indexing in NumPy Fancy & Boolean Indexing**

In [9]:
arr = np.array([10, 20, 30, 40, 50])
selected = arr[[1, 3, 4]]
print("Selected Elements:", selected)

Selected Elements: [20 40 50]


In [10]:
arr2D = np.array([[10, 20, 30], 
                  [40, 50, 60], 
                  [70, 80, 90]])
# Select rows at indices 0 & 2
selected_rows = arr2D[[0, 2]]
print("\nSelected Rows:\n", selected_rows)
# Select specific elements using row & column indices
selected_elements = arr2D[[0, 1], [2, 0]]  # (0,2) -> 30 and (1,0) -> 40
print("\nSelected Elements:", selected_elements)  # [30, 40]



Selected Rows:
 [[10 20 30]
 [70 80 90]]

Selected Elements: [30 40]


In [14]:
arr = np.array([5, 15, 25, 35, 45, 55,20])

# Get elements greater than 20
filtered = arr[arr > 20]
print("\nElements > 20:", filtered)  # [25, 35, 45, 55]
print(arr[arr % 2 == 0],arr[~((arr > 30) & (arr < 70))])


Elements > 20: [25 35 45 55]
[20] [ 5 15 25 20]


In [15]:
arm=np.array(arr[~((arr > 30) & (arr < 70))])
print(arm)

[ 5 15 25 20]


$Vectorization$ *allows you to apply operations to entire arrays at once, rather than looping through elements manually.*

In [16]:
arr = np.array([1, 2, 3, 4, 5])
# Vectorized operation (FAST)
result = arr * 2  
print("Vectorized Multiplication:", result)  # [2, 4, 6, 8, 10]

# Loop-based approach (SLOW)
result_loop = [x * 2 for x in arr]
print("Loop-Based Multiplication:", result_loop)  # [2, 4, 6, 8, 10]

Vectorized Multiplication: [ 2  4  6  8 10]
Loop-Based Multiplication: [2, 4, 6, 8, 10]


$Arithmetic\;operations$
- scaler
- ndarray

In [18]:
#scaler
arr = np.array([[10, 20, 30], 
                [40, 50, 60]])

scalar = 5
print("Array + Scalar:\n", arr + scalar)

Array + Scalar:
 [[15 25 35]
 [45 55 65]]


In [19]:
print(arr*5)
print(arr-5)
print(arr//2)
print(arr%3)

[[ 50 100 150]
 [200 250 300]]
[[ 5 15 25]
 [35 45 55]]
[[ 5 10 15]
 [20 25 30]]
[[1 2 0]
 [1 2 0]]


In [20]:
# array
arr1 = np.array([10, 20, 30])
arr2 = np.array([1, 2, 3])

print("Addition:", arr1 + arr2)  # [11, 22, 33]
print("Subtraction:", arr1 - arr2)  # [9, 18, 27]
print("Multiplication:", arr1 * arr2)  # [10, 40, 90]
print("Division:", arr1 / arr2)  # [10. 10. 10.]


Addition: [11 22 33]
Subtraction: [ 9 18 27]
Multiplication: [10 40 90]
Division: [10. 10. 10.]


**$NumPy \;is \;~100x \;faster \;than \;Python \;loops \;for \;large \;datasets!$**

In [21]:
import time

size = 10**6  # 1 million elements
arr = np.random.rand(size)

# Loop-based sum
start = time.time()
sum_loop = sum(arr)
print("Loop-based sum:", sum_loop, "Time:", time.time() - start)

# Vectorized sum
start = time.time()
sum_vectorized = np.sum(arr)
print("Vectorized sum:", sum_vectorized, "Time:", time.time() - start)

Loop-based sum: 500280.27949240647 Time: 0.20343947410583496
Vectorized sum: 500280.27949239145 Time: 0.0


## built-in functions

In [29]:
# Math Functions

arr = np.array([1, 4, 9, 16, 25])
print("Square Root:", np.sqrt(arr))  # [1. 2. 3. 4. 5.]
print("Exponential:", np.exp(arr))  # e^x for each element
print("Logarithm:", np.log(arr))  # Natural log of elements
print("Sine:", np.sin(arr))  # Sine values
print("Cosine:", np.cos(arr))  # Cosine values
print("Tangent:", np.tan(arr))  # Tangent values


Square Root: [1. 2. 3. 4. 5.]
Exponential: [2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10]
Logarithm: [0.         1.38629436 2.19722458 2.77258872 3.21887582]
Sine: [ 0.84147098 -0.7568025   0.41211849 -0.28790332 -0.13235175]
Cosine: [ 0.54030231 -0.65364362 -0.91113026 -0.95765948  0.99120281]
Tangent: [ 1.55740772  1.15782128 -0.45231566  0.30063224 -0.13352641]


In [3]:
 # Aggregation Functions

arr = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9]])
print("Sum:", np.sum(arr))  # 45
print("Mean:", np.mean(arr))  # 5.0
print("Max:", np.max(arr))  # 9
print("Min:", np.min(arr))  # 1
print("Standard Deviation:", np.std(arr))  # 2.58
print("Variance:", np.var(arr))  # 6.67


Sum: 45
Mean: 5.0
Max: 9
Min: 1
Standard Deviation: 2.581988897471611
Variance: 6.666666666666667


In [31]:
print("Row-wise Sum:", np.sum(arr, axis=1))  # [ 6 15 24] (Sum of each row)
print("Column-wise Mean:", np.mean(arr, axis=0))  # [4. 5. 6.] (Mean of each column)

Row-wise Sum: [ 6 15 24]
Column-wise Mean: [4. 5. 6.]


### **📌 Complete List of NumPy Operations** 🔥  
To master NumPy, it’s important to know **all the key operations** that can be performed. Below is a structured list covering everything from **basic operations** to **advanced mathematical functions**.  

---

## **🔹 1. Basic Arithmetic Operations (Element-wise)**
| Operation | Description | Example |
|-----------|------------|---------|
| `+` | Addition | `A + B` |
| `-` | Subtraction | `A - B` |
| `*` | Multiplication | `A * B` |
| `/` | Division | `A / B` |
| `//` | Floor Division | `A // B` |
| `%` | Modulus (Remainder) | `A % B` |
| `**` | Power | `A ** B` |
| `np.add(A, B)` | Addition (Function) | `np.add(A, B)` |
| `np.subtract(A, B)` | Subtraction (Function) | `np.subtract(A, B)` |
| `np.multiply(A, B)` | Multiplication (Function) | `np.multiply(A, B)` |
| `np.divide(A, B)` | Division (Function) | `np.divide(A, B)` |

---

## **🔹 2. Advanced Mathematical Operations**
| Operation | Description | Example |
|-----------|------------|---------|
| `np.sqrt(A)` | Square Root | `np.sqrt(A)` |
| `np.exp(A)` | Exponential (e^x) | `np.exp(A)` |
| `np.log(A)` | Natural Logarithm | `np.log(A)` |
| `np.log10(A)` | Base-10 Logarithm | `np.log10(A)` |
| `np.power(A, B)` | Power (A^B) | `np.power(A, B)` |
| `np.abs(A)` | Absolute Value | `np.abs(A)` |
| `np.round(A, n)` | Rounding | `np.round(A, 2)` |
| `np.ceil(A)` | Round Up | `np.ceil(A)` |
| `np.floor(A)` | Round Down | `np.floor(A)` |

---

## **🔹 3. Trigonometric & Hyperbolic Functions**
| Operation | Description | Example |
|-----------|------------|---------|
| `np.sin(A)` | Sine | `np.sin(A)` |
| `np.cos(A)` | Cosine | `np.cos(A)` |
| `np.tan(A)` | Tangent | `np.tan(A)` |
| `np.arcsin(A)` | Inverse Sine | `np.arcsin(A)` |
| `np.arccos(A)` | Inverse Cosine | `np.arccos(A)` |
| `np.arctan(A)` | Inverse Tangent | `np.arctan(A)` |
| `np.sinh(A)` | Hyperbolic Sine | `np.sinh(A)` |
| `np.cosh(A)` | Hyperbolic Cosine | `np.cosh(A)` |
| `np.tanh(A)` | Hyperbolic Tangent | `np.tanh(A)` |

---

## **🔹 4. Aggregation Functions**
| Operation | Description | Example |
|-----------|------------|---------|
| `np.sum(A)` | Sum of all elements | `np.sum(A)` |
| `np.prod(A)` | Product of all elements | `np.prod(A)` |
| `np.mean(A)` | Mean (Average) | `np.mean(A)` |
| `np.median(A)` | Median | `np.median(A)` |
| `np.var(A)` | Variance | `np.var(A)` |
| `np.std(A)` | Standard Deviation | `np.std(A)` |
| `np.min(A)` | Minimum Value | `np.min(A)` |
| `np.max(A)` | Maximum Value | `np.max(A)` |
| `np.percentile(A, p)` | Percentile | `np.percentile(A, 75)` |

---

## **🔹 5. Matrix & Linear Algebra Operations**
| Operation | Description | Example |
|-----------|------------|---------|
| `np.dot(A, B)` | Dot Product | `np.dot(A, B)` |
| `A @ B` | Matrix Multiplication | `A @ B` |
| `np.matmul(A, B)` | Matrix Multiplication | `np.matmul(A, B)` |
| `np.linalg.inv(A)` | Inverse of a Matrix | `np.linalg.inv(A)` |
| `np.linalg.det(A)` | Determinant of a Matrix | `np.linalg.det(A)` |
| `np.linalg.eig(A)` | Eigenvalues & Eigenvectors | `np.linalg.eig(A)` |
| `np.transpose(A)` | Transpose | `A.T` |
| `np.linalg.solve(A, B)` | Solves Ax = B | `np.linalg.solve(A, B)` |

---

## **🔹 6. Logical & Comparison Operations**
| Operation | Description | Example |
|-----------|------------|---------|
| `A > B` | Greater Than | `A > B` |
| `A < B` | Less Than | `A < B` |
| `A == B` | Equal To | `A == B` |
| `A != B` | Not Equal To | `A != B` |
| `np.logical_and(A, B)` | Logical AND | `np.logical_and(A, B)` |
| `np.logical_or(A, B)` | Logical OR | `np.logical_or(A, B)` |
| `np.logical_not(A)` | Logical NOT | `np.logical_not(A)` |

---

## **🔹 7. Array Manipulation Operations**
| Operation | Description | Example |
|-----------|------------|---------|
| `A.reshape(m, n)` | Reshape an array | `A.reshape(2,3)` |
| `A.flatten()` | Flatten a multi-dimensional array | `A.flatten()` |
| `A.ravel()` | Flatten an array (Memory efficient) | `A.ravel()` |
| `A.T` | Transpose of an array | `A.T` |
| `np.hstack((A, B))` | Horizontal Stacking | `np.hstack((A, B))` |
| `np.vstack((A, B))` | Vertical Stacking | `np.vstack((A, B))` |
| `np.concatenate((A, B), axis=0)` | Concatenate Arrays | `np.concatenate((A, B), axis=0)` |
| `np.split(A, n, axis=0)` | Split an Array | `np.split(A, 3, axis=0)` |

---

## **🔹 8. Random Number Generation (`np.random`)**
| Operation | Description | Example |
|-----------|------------|---------|
| `np.random.rand(n)` | Random numbers (Uniform) | `np.random.rand(5)` |
| `np.random.randn(n)` | Random numbers (Normal) | `np.random.randn(5)` |
| `np.random.randint(low, high, size)` | Random Integers | `np.random.randint(1, 10, (2,3))` |
| `np.random.choice(A, size)` | Random Selection from an Array | `np.random.choice(A, 3)` |
| `np.random.shuffle(A)` | Shuffle an Array | `np.random.shuffle(A)` |
| `np.random.seed(n)` | Set Seed for Reproducibility | `np.random.seed(42)` |

---

## **📌 Summary**
This list covers **ALL** major NumPy operations **needed for ML & Data Science**. 🚀  

In [6]:
arr = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9]])

In [12]:
print(np.max(arr,axis=0)+np.max(arr,axis=1))

[10 14 18]


In [27]:
arr=arr.reshape(1,9)
print(arr)
print(arr.shape)
arr=arr.reshape(-1)

[[1 2 3 4 5 6 7 8 9]]
(1, 9)


In [28]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

## Broadcasting
**NumPy automatically expands arrays of different shapes to match each other when performing element-wise operations.**

In [29]:
A = np.array([[1, 2, 3], [4, 5, 6]])  # Shape (2,3)
B = 10  # Scalar

print(A + B)

[[11 12 13]
 [14 15 16]]


In [38]:
A = np.ones((3,1,4))  # Shape (3,1,4)
B = np.ones((1, 2, 4))  # Shape (1,2,4)

print(A )  # Resulting shape is (3,2,4)


[[[1. 1. 1. 1.]]

 [[1. 1. 1. 1.]]

 [[1. 1. 1. 1.]]]


In [53]:
#exesice problem

arr=np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12]])
print(arr+[100,200,300,400])
arr=np.ones((4,1))
print(arr*[4,4,4,4])
try:
    
    print(arr + np.array([[1, 2, 3], [4, 5, 6]]))  # Shape mismatch error
except ValueError as e:
    print("Error:", e)

[[101 202 303 404]
 [105 206 307 408]
 [109 210 311 412]]
[[4. 4. 4. 4.]
 [4. 4. 4. 4.]
 [4. 4. 4. 4.]
 [4. 4. 4. 4.]]
Error: operands could not be broadcast together with shapes (4,1) (2,3) 


In [6]:
# a=np.array([1,2,3,4,5])
# b=np.array([6,7,8,9,10])
# print(np.concatenate((a,b),axis=0)